apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources mengarah ke file hasil generate Podman
resources:
  - deployment.yaml

# Common labels untuk semua resource
commonLabels:
  app: my-awesome-app
  env: base
