apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

commonLabels:
  env: dev

# Opsional: patch image untuk dev (uncomment dan sesuaikan setelah generate kube)
# images:
#   - name: localhost/my-awesome-app:dev
#     newTag: dev
